import { StyleSheet } from 'react-native';

export const unionStyles = StyleSheet.create({
  listSection: {
    width: '100%',
    marginTop: 8,
  },
  toolbar: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: 16,
    zIndex: 10,
  },
  fileCount: {
    fontSize: 18,
    fontWeight: '700',
    color: '#111111',
    marginTop: 8,
  },
  toolbarActions: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
  },
  sortButton: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 12,
    backgroundColor: '#f7f7f7',
    borderWidth: 1,
    borderColor: '#e8e8e8',
    marginTop: 4,
  },
  sortButtonText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#333333',
  },
  addMenuWrapper: {
    position: 'relative',
    alignItems: 'flex-end',
  },
  addButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#ff4a36',
    alignItems: 'center',
    justifyContent: 'center',
  },
  addButtonText: {
    color: '#ffffff',
    fontSize: 26,
    fontWeight: '300',
    lineHeight: 28,
    marginTop: -2,
  },
  dropdownMenu: {
    position: 'absolute',
    top: 46,
    right: 0,
    minWidth: 260,
    backgroundColor: '#ffffff',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e8e8e8',
    overflow: 'hidden',
    zIndex: 20,
  },
  reorderHint: {
    width: '100%',
    fontSize: 13,
    color: '#ff4a36',
    marginBottom: 12,
    textAlign: 'center',
    lineHeight: 18,
  },
  fileRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
    paddingVertical: 14,
    paddingHorizontal: 12,
  },
  fileRowDragging: {
    borderWidth: 2,
    borderColor: '#ff4a36',
    backgroundColor: '#fff5f4',
  },
  fileRowDropTarget: {
    borderWidth: 1,
    borderColor: '#ffb8ae',
    borderStyle: 'dashed',
  },
  orderBadge: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#ff4a36',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
  },
  orderBadgeText: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '700',
  },
  gripButton: {
    paddingHorizontal: 6,
    paddingVertical: 8,
    marginRight: 4,
  },
  gripIcon: {
    fontSize: 20,
    color: '#888888',
  },
  fileInfo: {
    flex: 1,
    paddingRight: 8,
  },
  rowActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
  },
  moveButton: {
    width: 32,
    height: 32,
    borderRadius: 8,
    backgroundColor: '#eeeeee',
    alignItems: 'center',
    justifyContent: 'center',
  },
  moveButtonDisabled: {
    opacity: 0.35,
  },
  moveButtonText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#444444',
  },
  deleteButton: {
    padding: 6,
    marginLeft: 4,
  },
  deleteText: {
    fontSize: 18,
    fontWeight: '700',
    color: '#ff4a36',
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 14,
    paddingHorizontal: 16,
    backgroundColor: '#ffffff',
  },
  menuItemText: {
    flex: 1,
    fontSize: 15,
    color: '#111111',
    fontWeight: '600',
  },
  menuDivider: {
    height: 1,
    backgroundColor: '#eeeeee',
  },
  mergeButton: {
    marginTop: 8,
  },
  progressSection: {
    width: '100%',
    alignItems: 'center',
    marginTop: 40,
  },
  progressCircle: {
    width: 140,
    height: 140,
    borderRadius: 70,
    borderWidth: 8,
    borderColor: '#ff4a36',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  progressPercent: {
    fontSize: 36,
    fontWeight: 'bold',
    color: '#ff4a36',
  },
  progressLabel: {
    fontSize: 12,
    color: '#666666',
    marginTop: 4,
  },
  resultSection: {
    width: '100%',
    alignItems: 'center',
    marginTop: 40,
  },
  resultTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#111111',
    textAlign: 'center',
    marginBottom: 28,
    lineHeight: 32,
  },
});
